compressionLevel: mixed

enableGlobalCache: false

enableTelemetry: false

nodeLinker: node-modules

npmAlwaysAuth: true

npmAuthToken: "${JFROG_ACCESS_TOKEN}"

npmRegistryServer: "https://appfolio.jfrog.io/artifactory/api/npm/appfolio-react-gears-npm/"

yarnPath: .yarn/releases/yarn-4.10.3.cjs
