nodeLinker: node-modules
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
yarnPath: .yarn/releases/yarn-3.2.2.cjs
npmRegistryServer: https://appfolio-ecr-195334327833.d.codeartifact.us-west-2.amazonaws.com/npm/appfolio-repo/
npmAlwaysAuth: true
enableTelemetry: false
npmAuthToken: ${CODEARTIFACT_AUTH_TOKEN}
