compressionLevel: mixed

enableGlobalCache: false

enableTelemetry: false

nodeLinker: node-modules

npmAlwaysAuth: true

npmAuthToken: "${CODEARTIFACT_AUTH_TOKEN}"

npmRegistryServer: "https://appfolio-ecr-195334327833.d.codeartifact.us-west-2.amazonaws.com/npm/appfolio-repo/"

yarnPath: .yarn/releases/yarn-4.10.3.cjs
