version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            - v1-npm-deps
      - run:
          name: Install Dependencies
          command: rm -rf ./node-modules && npm install
      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Run Tests
          command: npm test
