export const shadow: string;
export const overflow-right: string;
export const overflowRight: string;
export const overflow-left: string;
export const overflowLeft: string;
export const overflow-bottom: string;
export const overflowBottom: string;
export const overflow-top: string;
export const overflowTop: string;
