import {
  Breadcrumb,
  BreadcrumbItem,
  Button,
  ButtonDropdown,
  ButtonGroup,
  ButtonToolbar,
  Card,
  CardBlock,
  CardColumns,
  CardDeck,
  CardFooter,
  CardGroup,
  CardHeader,
  CardImg,
  CardImgOverlay,
  CardLink,
  CardSubtitle,
  CardText,
  CardTitle,
  Col,
  Container,
  Dropdown,
  DropdownItem,
  DropdownMenu,
  DropdownToggle,
  Fade,
  Form,
  FormFeedback,
  FormGroup,
  FormText,
  Input,
  InputGroup,
  InputGroupAddon,
  InputGroupButton,
  Jumbotron,
  Label,
  ListGroup,
  Media,
  Modal,
  ModalBody,
  ModalFooter,
  ModalHeader,
  Nav,
  NavDropdown,
  NavItem,
  NavLink,
  Navbar,
  NavbarBrand,
  NavbarToggler,
  Pagination,
  PaginationItem,
  PaginationLink,
  Popover,
  PopoverContent,
  PopoverTitle,
  Progress,
  Row,
  TabContent,
  TabPane,
  Table,
  Tag,
  TetherContent,
  Tooltip } from 'reactstrap';

// Gears:

//import Address from './components/Address.js';
import Alert from './components/Alert.js';
import BlockPanel from './components/BlockPanel.js';
import CurrencyInput from './components/CurrencyInput.js';
import Datapair from './components/Datapair.js';
import DateMonth from './components/datemonth/DateMonth.js';
//import Dropdown2 from './components/Dropdown2.js';
import Flag from './components/Flag.js';
import FormChoice from './components/FormChoice.js';
import FormRow from './components/FormRow.js';
import HelpBubble from './components/HelpBubble.js';
import Icon from './components/Icon.js';
import PatternInput from './components/PatternInput.js';
//import SummaryBox from './components/SummaryBox.js';
//import SummaryBoxItem from './components/SummaryBoxItem.js';
//import UnitPropertyCard from './components/UnitPropertyCard.js';

export {
  // reactstrap
  Breadcrumb,
  BreadcrumbItem,
  Button,
  ButtonDropdown,
  ButtonGroup,
  ButtonToolbar,
  Card,
  CardBlock,
  CardColumns,
  CardDeck,
  CardFooter,
  CardGroup,
  CardHeader,
  CardImg,
  CardImgOverlay,
  CardLink,
  CardSubtitle,
  CardText,
  CardTitle,
  Col,
  Container,
  Dropdown,
  DropdownItem,
  DropdownMenu,
  DropdownToggle,
  Fade,
  Form,
  FormFeedback,
  FormGroup,
  FormText,
  Input,
  InputGroup,
  InputGroupAddon,
  InputGroupButton,
  Jumbotron,
  Label,
  ListGroup,
  Media,
  Modal,
  ModalBody,
  ModalFooter,
  ModalHeader,
  Nav,
  NavDropdown,
  NavItem,
  NavLink,
  Navbar,
  NavbarBrand,
  NavbarToggler,
  Pagination,
  PaginationItem,
  PaginationLink,
  Popover,
  PopoverContent,
  PopoverTitle,
  Progress,
  Row,
  TabContent,
  TabPane,
  Table,
  Tag,
  TetherContent,
  Tooltip,

  // Gears
  Alert,
  BlockPanel,
  CurrencyInput,
  Datapair,
  DateMonth,
//  Dropdown2, // TODO temp
  Flag,
  FormChoice,
  FormRow,
  HelpBubble,
  Icon, // TODO alias is visible in example code?
  PatternInput,
//  Address,
// SummaryBox,
// SummaryBoxItem
// UnitPropertyCard TODO
};
