name: Update docs for release
on:
  push:
    branches:
      - release-*
jobs:
  prepare-dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '*'
          check-latest: true
      - name: Install dependencies
        run: npm ci
      - name: Prepare dist
        run: npm run docs
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "docs: update storybook for ${{ steps.extract_branch.outputs.branch }}"
