import { configureActions } from '@storybook/addon-actions';

import './Welcome';
import './Layout';

import './ActivityLog';
import './Address';
import './Alerts';
import './Badge';
import './BlockPanel';
import './Breadcrumb';
import './Buttons';
import './Callout';
import './Card';
import './Carousel';
import './CheckboxGroup';
import './Collapse';
import './CollapsableText';
import './Combobox';
import './CreditCardNumber';
import './CurrencyInput';
import './Datapair';
import './DateInput';
import './Dropdown';
import './ExpandableSection';
import './Fade';
import './FeatureBanner';
import './FilterList';
import './FormRow';
import './FormLabelGroup';
import './Forms';
import './HasManyFields';
import './HelpBubble';
import './Highlight';
import './Icon';
import './ImageCarousel';
import './Input';
import './InfoBox';
import './InputGroup';
import './LabelBadge';
import './ListGroup';
import './MaskedInput';
import './Media';
import './Modal';
import './MonthInput';
import './Nav';
import './Navbar';
import './Note';
import './Notes';
import './Pagination';
import './Paginator';
import './Popover';
import './Progress';
import './RadioGroup';
import './ScrollContainer';
import './Select';
import './Spinner';
import './Steps';
import './SummaryBox';
import './Table';
import './TimeInput';
import './Toast';
import './Tooltip';
import './Waiting';

import './More';

configureActions({ depth: 5 });
